#!/usr/bin/python -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500
DATA_SIZE = 1430
TIMEOUT = .1
TOTAL_TIMEOUT = 30
SEQUENCE = 0
START = time.time()

# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(TIMEOUT)

window = 500
packets_in_flight = {}  # {Sequence : data}
last_resent = time.time()

def log(string):
    sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")


def send_next_packet():
    global SEQUENCE
    allowed_to_send = window - len(packets_in_flight)
    for i in range(0, allowed_to_send):
        data = sys.stdin.read(DATA_SIZE)
        if len(data) > 0:
            msg = json.dumps({"sequence": int(SEQUENCE), "data": data, "eof": False})
            packets_in_flight[int(SEQUENCE)] = data
            SEQUENCE += len(data)
            send_msg(msg, data)
        else:
            log("NO MORE DATA")
            return False
    return True


def send_msg(msg, data):
    if sock.sendto(msg, dest) < len(msg):
        log("[error] unable to fully send packet")
    else:
        log("[send data] " + msg)


def send_last_packet_in_flight():
    global window
    msg = json.dumps({"sequence": min(packets_in_flight), "data": packets_in_flight[min(packets_in_flight)], "eof": False})
    send_msg(msg, packets_in_flight[min(packets_in_flight)])
    window = max(window - 1, 1)
    main()


def recieve_ack():
    global window
    window += 1
    del packets_in_flight[min(packets_in_flight)]


def finish_program():
    for i in range(0, 10):
        sock.sendto(json.dumps({"eof": True}), dest)
    sys.exit(0)


def main():
    # Now read in data, send packets
    try:
        while True:
            log("ABOUT TO SLEEP")
            if time.time() - START > TOTAL_TIMEOUT:
                sys.exit(-1)

            result = sock.recvfrom(MSG_SIZE)
            if result:
                (data, addr) = result
                try:
                    #log("got data")

                    decoded = json.loads(data)
                    # If there is an ack, send next packet
                    if decoded['ack'] == (min(packets_in_flight) + len(packets_in_flight[min(packets_in_flight)])):
                        log("[recv ack] " + str(min(packets_in_flight) + len(packets_in_flight[min(packets_in_flight)])))
                        recieve_ack()

                        # Try to send next packet; break if no more data
                        if not send_next_packet() and not packets_in_flight:
                            log("COMPLETE")
                            finish_program()
                            break
                        continue
                    else:
                        log("ACK NOT SEQ MINE")
                        log(json.dumps(SEQUENCE))
                        log(json.dumps(decoded))
                except (ValueError, KeyError, TypeError):
                    log("[recv corrupt packet]")
    except socket.timeout:
        global last_resent
        if time.time() - last_resent > TIMEOUT:
            last_resent = time.time()
            log("resending packets")
            send_last_packet_in_flight()

# Send first packet
send_next_packet()
main()